<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
 //        if (!window.checkoutConfig.isCustomerLoggedIn){
 //         document.getElementById('customer-email').removeAttribute("disabled")
 // }

    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        })
    </script>
    <script type="text/javascript">
        require(['jquery', 'myfile'], function($, hello) {
            hello();
        });
    </script>
<!--    <ul class="my-list">-->
<!--        <li>1st Element</li>-->
<!--        <li>2nd Element</li>-->
<!--        <li>3rd Element</li>-->
<!--        <li>4th Element</li>-->
<!--        <li>5th Element</li>-->
<!--        <li>6th Element</li>-->
<!--        <li>7th Element</li>-->
<!--        <li>8th Element</li>-->
<!--    </ul>-->
<!---->
<!--    <script>-->
<!--        require([-->
<!--            'jquery',-->
<!--            'slick'-->
<!--        ], function ($) {-->
<!--            $(document).ready(function () {-->
<!--                $(".my_list").slick({-->
<!--                    dots: true,-->
<!--                    infinite: true,-->
<!--                    speed: 300,-->
<!--                    slidesToShow: 4,-->
<!--                    slidesToScroll: 1-->
<!--                });-->
<!--            });-->
<!--        });-->
<!--    </script>-->
</div>
