<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>


<div id="slider-wrapper">
    <ul  id="my_list" class="my_list">

    </ul>
</div>
<script type="text/x-magento-init">
       {
           ".my_list": {
               "Magento_Cms/js/slider": {}
           }
       }
</script>
